### PR TITLE
feat(jupyter): Update list of containers

### PR DESCRIPTION
**Pull request by sylus**
Hey @zachomedia does this look good?

Is the new generated list of @blairdrummond containers.

### CODE REVIEW

**Review by zachomedia — DISMISSED** [review]
This LGTM

**Comment by sylus** [comment]
@zachomedia why did i need to update this configmap?

```
❯ kubectl edit configmap -n kubeflow  jupyter-web-app-jupyter-web-app-config  
```

**Comment by sylus** [comment]
@zachomedia basically why is jupyter-web-app doubled? hope wasn't something we did but this is the configmap the jupyter-apis image is using and not the single one.

```
jupyter-web-app-config                           1      213d
jupyter-web-app-jupyter-web-app-config           1      3d19h
```

**Comment by zachomedia** [comment]
Maybe it's a change in the manifests? I can dig through the manifests when I have a chance and try to understand why it's coming out like that. Nothing in the diff stood out as being able to cause that.

**Pull request merged**
