### PR TITLE
Update spawner_ui_config.yaml

### PR DESCRIPTION
**Pull request by Souheil-Yazji**
Image tags reference long-lived tag ```v1``` instead of commit SHA

### CODE REVIEW

**Review by cboin1996 — COMMENTED** [review]
What is the reasoning for long lived tags rather than the commit sha?

**Comment by Souheil-Yazji** [comment]
> What is the reasoning for long lived tags rather than the commit sha?

According to @Jose-Matsuda:
- we don't need to update the configmap with the new sha each time we merge into master
- makes the task of restarting notebooks to get users on the latest image (whether it be due to CVE's or bug fixes) easier since we can just restart the statefulset (this assumes the `imagePullPolicy` is `Always` on the pod, which will be made the default on prod eventually (it already is on dev)

**Comment by cboin1996** [comment]
Ok sounds good, in that case, this LGTM.

**Review by cboin1996 — APPROVED** [review]
Ok sounds good, in that case, this LGTM.

**Comment by Souheil-Yazji** [comment]
For reference, images will also retain the sha tag, so in the case of a revert, those can be referenced via commit: 
image

**Pull request merged**
