### PR TITLE
Update jupyter-api image and add Listen_address env variable

### PR DESCRIPTION
**Pull request by wg102**
fixes https://github.com/StatCan/kubeflow-manifest/issues/39

### CODE REVIEW

**Comment by brendangadd** [comment]
New environment variable `LISTEN_ADDRESS` required due to StatCan/jupyter-apis#15.

**Review by justbert — APPROVED** [review]

**Comment by justbert** [comment]
@brendangadd We usually only merge in after-hours to prevent downtime of the Kubeflow Control plane. That still okay?

**Review by brendangadd — APPROVED** [review]

**Comment by justbert** [comment]
@sylus do we need to change anything else for this?

**Comment by sylus** [comment]
Thinking will merge over weekend as wont have time to debug any issues before then.

**Comment by justbert** [comment]
@sylus was gonna do it last night, but @brendangadd pointed out there may be something missing:

> The new environment variable is in params.env, but I'm wondering if it also needs to be referenced somewhere else, like here: https://github.com/StatCan/kubeflow-manifest/blob/master/kustomize/jupyter-web-app/base/kustomization.yaml#L27

**Comment by brendangadd** [comment]
### Reason for environment variable

The jupyter-apis image has been modified so that the listen address is configurable. StatCan/jupyter-apis#15.

* Old behaviour: listen on `0.0.0.0:5000`
* New behaviour: order of precedence of `-listen-address` CLI arg > `LISTEN_ADDRESS` env var > default of `127.0.0.1:5000` 

This PR needs to add the new `LISTEN_ADDRESS` env var, set to `0.0.0.0:5000`, to maintain the original (desired) behaviour in prod.

/cc @justbert @sylus

**Comment by justbert** [comment]
@sylus Can you take a look at this? I'm not familiar with the components of the DAaaS platform.

**Comment by justbert** [comment]
Brought up by @brendangadd:

> kubectl kustomize and kustomize build do not behave the same! https://github.com/kubernetes-sigs/kustomize/issues/2205 (edited)

**Comment by sylus** [comment]
So the P.R. looks fine and nothing looks wrong to me. As long as Zach has everything committed properly it should be fine.

This has been testing and confirmed to work?

**Comment by sylus** [comment]
So this change brings in the new jupyter-api of which the delta is quite large?

https://github.com/StatCan/jupyter-apis/compare/3c844b43b96119beea3a110689ec97b0b3d85993...692c8f49222460fc9fcf5d6c5ea80e25f462de87

I guess the mitigation is if things don't work we set back the image version?

**Comment by brendangadd** [comment]
@sylus 
* The manifest updates have not been tested. Not sure how to test that out properly with only the one cluster.
* I verified that the new env var exists in the kustomize-generated config map as expected, so should have the same behaviour as the ROK_SECRET_NAME.
* The fallback mechanism for setting the listen address in the Go app has been tested.
* The other jupyter-apis changes have been tested.

**Review by sylus — DISMISSED** [review]

**Comment by sylus** [comment]
@zachomedia can i merge this? Should we update the SHA do the latest?

**Review by zachomedia — CHANGES_REQUESTED** [review]
I feel like we should make this environment variable value the default in the `Dockerfile` rather than setting it on the cluster. It'll will be needed to run in Docker anyways to expose the app.

Thoughts @sylus @justbert ?

**Comment by sylus** [comment]
@saffaalvi can u make this change? then can merge!

**Review by zachomedia — APPROVED** [review]
LGTM!

**Pull request merged**
