### PR TITLE
upgrade mpi 1.6

### LINKED ISSUE #252: Upgrade 1.6 Apps: mpi-job
Upgrade Mpi-job is now apart of training-operator. We can get rid of this component.

### PR DESCRIPTION
**Pull request by rohank07**
closes #252 
mpi-job has been moved into tf-training. We can get rid of the mpi-job, mx-net and pytorch component and continue to upgrade tf-training.
Ref: https://github.com/kubeflow/manifests/pull/2123#issuecomment-1036077615
https://github.com/kubeflow/manifests/issues/1962#issuecomment-899662895

### CODE REVIEW

**Review by sylus — CHANGES_REQUESTED** [review]
Can our folder restructure also match the new naming ?

Also i have no idea what you mean remove pytorch that is a different component entirely then this P.R. addresses

Do you mean training-operator now calls all those components?

**Comment by rohank07** [comment]
Yeah v1.4 they have a universal operator that supports all frameworks, getting rid of pytorch, mxnet and xgboost operator. 
Mpi-job is wrapped into tf-training

**Comment by sylus** [comment]
This file needs to be deleted

[kustomize/apps/tf-training/base/kustomization.yaml](https://github.com/StatCan/aaw-kubeflow-manifests/pull/260/files#diff-687dff95472faaf2ce5f9a8468008f3befd60ac442e8bb302352d3fc79dd2cf5)

**Comment by sylus** [comment]
Sorry last thing

/training-operator/


We need to call training-operator name as well instead of tf-operator.

**Review by sylus — APPROVED** [review]

**Pull request merged**
