### PR TITLE
feat(api): Switch to go backend for Jupyter

### PR DESCRIPTION
**Pull request by sylus**

### CODE REVIEW

**Comment by sylus** [comment]
Hey @zachomedia can u approve this? 

Looks good?

**Comment by zachomedia** [comment]
@sylus I think we want to change it here? https://github.com/StatCan/kubeflow-manifest/blob/master/kustomize/jupyter-web-app/base/kustomization.yaml#L18..L20

**Comment by sylus** [comment]
@zachomedia better?

**Comment by zachomedia** [comment]
@sylus I think you edited the wrong file, that is `application` not `jupyter-web-app`

**Comment by sylus** [comment]
Last attempt or give up @zachomedia

**Pull request merged**
