### PR TITLE
upgrade profiles (1.3.1 --> 1.4.1)

### LINKED ISSUE #213: Upgrade 1.4.1 Apps: profiles
## Overview

**EPIC**: [Kubeflow Upgrade Planning][epic-kubeflow]

| Component          | Local Manifests Path                                  | Upstream | Initial Work |
| ------------------ | ----------------------------------------------------- | -------- | ------------ |
| profiles | [apps/profiles][local-profiles]    | `v1.4.1` |              |

[epic-kubeflow]: https://github.com/StatCan/aaw-kubeflow-manifests/issues/1203
[local-profiles]: https://github.com/StatCan/aaw-kubeflow-manifests/tree/main/kustomize/apps/profiles

## Adjustments

- 1.3.1
  - Bring in imagePullSecrets, and kfam :latest image
- 1.4.1
  - No longer using configmap generator

## Kubeflow V2 Manifests

The following is the kustomize that was used in Kubeflow V2:

- https://github.com/StatCan/aaw-kubeflow-manifests/tree/master/kustomize/application/profiles

```sh
apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: gcr.io/kubeflow-images-public/kfam
  newName: k8scc01covidacr.azurecr.io/kfam
  newTag: latest
kind: Kustomization
namespace: kubeflow
patchesStrategicMerge:
- deployment.yaml
resources:
- ../../../.cache/manifests/manifests-1.2-branch/profiles/base_v3
```

## AAW Dev / Prod Live Manifests

At the moment there is no difference in state then what is overridden above.

> **Note**: While most everything 95% would have been automated, stored as config and is using what is referenced above. I believe a few things could have been done as manual adjustments that we should make sure we are keeping. Largely any manual yaml adjustments would have been documented in high level GitHub issues or tracked in the YAML repository under the AAW group.

## Kubeflow V3 Manifests

The following is the P.R. that will be merged into the main branch for Kubeflow V3:

- #141 

```sh
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
- github.com/kubeflow/manifests/apps/profiles/upstream/overlays/kubeflow?ref=v1.4.1


patchesStrategicMerge:
- deployment.yaml

images:
- name: gcr.io/kubeflow-images-public/kfam
  newName: k8scc01covidacr.azurecr.io/kfam
  newTag: latest


```

## Testing

Usually a good idea to make sure all of the overrides are working is to run the following command and verify all of the yaml output for the component is what you expect and all of the overrides are taken into account.

- Deployment with imagePullSecrets ouputted successfully

```sh
task stack:aaw:preview
```

> **Note**: The command above will render all of the manifests into manifests top level folder with the name `aaw.yaml`. A trick to keep the yaml output small is under `stacks/aaw/kustomization.yaml` to only have the component you wish to test referenced.

### PR DESCRIPTION
**Pull request by bryanpaget**
This is part of the Kubeflow 1.4 Upgrade Epic (https://github.com/StatCan/daaas/issues/1203) and resolves the following upgrade issue: https://github.com/StatCan/aaw-kubeflow-manifests/issues/213.

### CODE REVIEW

**Review by sylus — COMMENTED** [review]
Hey @bryanpaget 

So this looks good for the most part just two questions?

a) It looks like we removed Istio Injection?
b) The new image is just called 1.4 and not in semver format?

Screen Shot 2022-09-05 at 4 05 40 PM

**Review by sylus — CHANGES_REQUESTED** [review]
I think we need to add the istio back and just check that the tag name is ok.

**Comment by rohank07** [comment]
Verifying that the tag name is v1.4: https://github.com/kubeflow/manifests/blob/v1.4.1/apps/profiles/upstream/overlays/kubeflow/kustomization.yaml#L31
The istio-injection label was removed in order to debug an issue on AAW Kubeflow. Adding the patch did not fix it (from v1.6), therefore we are reverting.

**Review by sylus — APPROVED** [review]
Okay as long as are sure :)

**Pull request merged**
