### PR TITLE
feat(kfam): Use custom kfam component until kubeflow/kubeflow!5202 is merged

### PR DESCRIPTION
**Pull request by zachomedia**

### CODE REVIEW

**Comment by sylus** [comment]
Where is the docekr container for this?

**Comment by zachomedia** [comment]
Thanks @sylus for the reminder to document that:

The change was applied in this commit:

https://github.com/StatCan/kubeflow/commit/7f40cf4ee5968738be45cf0c40a98ace54beb237

Built and pushed with:

```sh
make IMG=k8scc01covidacr.azurecr.io/kfam TAG=latest build push
```

Since this should get committed upstream, we decided not to setup an automated build pipeline for this.

**Comment by sylus** [comment]
Is there a PR?

**Comment by sylus** [comment]
Oh yeah i remember NM.

**Pull request merged**
